### ISSUE TITLE
multiply gpu support

### ISSUE THREAD

**Issue by maozhiqiang** [bfs18/nsynth_wavenet#1]
@bfs18 Good job! 
single gpu training is very slowing ! how to use multiply GPU to training

**Comment by zhang-jian** [comment]
I believe this implementation is based on https://github.com/tensorflow/magenta/tree/master/magenta/models/nsynth/wavenet, which uses an internal version of tensorflow for distributed training, see https://github.com/tensorflow/magenta/issues/625.

However, I haven't look at what are the exact difference between these two regarding to distributed training. It is possible that there are updates in this implementation which make the distributed training working. Maybe the project owner can clarify this.

**Comment by maozhiqiang** [comment]
OK ! thanks@zhang-jian

**Comment by bfs18** [comment]
Hi, I added multi-gpu support. It only supports single worker with multiple gpu and does not support a cluster of workers since I don't have that much devices.
All you need to do is specify the gpu_ids when running the train_*.py scripts.

**Comment by bfs18** [comment]
The multi-gpu implement is not quiet efficient at syncing gpus. So it takes much longer to run a single step (about doubles the time). Trying to improve it.

**Comment by maozhiqiang** [comment]
@bfs18 thanks! I will try it!

**Comment by maozhiqiang** [comment]
do you get reasonable results for parallel wavenet! @bfs18

**Comment by bfs18** [comment]
not yet.
