### ISSUE TITLE
Loss is a negative number 

### ISSUE THREAD

**Issue by maozhiqiang** [bfs18/nsynth_wavenet#12]
hi @bfs18 , When training use wavenet_gauss,json, The loss is a negative number, Is this normal？

**Comment by bfs18** [comment]
Hi, It OK, because the loss is a negative log probability density function. The value of a pdf can be larger than 1.0. So -log(pdf) can be a negative number. MOL loss is a negative log cumulative probability function.  The value of  cdf is always in [0.0, 1.0], so MOL loss is always lager than 0.0.

**Comment by maozhiqiang** [comment]
@bfs18!  thanks !
