### ISSUE TITLE
can't play the example audio

### ISSUE THREAD

**Issue by NewEricWang** [bfs18/nsynth_wavenet#17]
Hi, 
    I have tried to play your given example audio. But it failed to be play. My player can't recognize its format.

**Comment by bfs18** [comment]
Hi,
If Sox is installed on a linux computer, you can run `play xxx.wav` to play the audio sample.
On windows, Potplayer can play the audio.

**Comment by NewEricWang** [comment]
I run the command:
play ../Desktop/gen_LJ001-0001.wav

An error is reported:
play FAIL formats: can't open input file `../Desktop/gen_LJ001-0001.wav': WAVE: RIFF header not found

The example audio is got from:
https://github.com/bfs18/nsynth_wavenet/tree/master/tests/pred_data-no_mu_law%2Bmol

**Comment by NewEricWang** [comment]
Ok, Thank you!
