### ISSUE TITLE
ResourceExhaustedError when training wavenet

### ISSUE THREAD

**Issue by ghostcow** [bfs18/nsynth_wavenet#2]
Hi,

I'm trying to run train_wavenet.py with config wavenet_mol.json and default settings.

I'm getting this error: 
```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [] and type float
         [[Node: dilated_conv_1/W/Initializer/random_uniform/sub = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [] values: 0.0883883461>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

Also when training with wavenet_ce.json. What could be the problem?

My setup is a single V100 GPU, tensorflow 1.8.0, cuda 9.0

**Comment by maozhiqiang** [comment]
the batch size is to bing, You can make it small
