### ISSUE TITLE
teacher_wavenet also noise

### ISSUE THREAD

**Issue by maozhiqiang** [bfs18/nsynth_wavenet#7]
I training  wavenet use English dataset, when 257546 steps!  the generate is noise!

the mel like this!
![test](https://user-images.githubusercontent.com/23501322/42551621-c5703ed0-850a-11e8-9a2e-9afd9eafc358.png)

**Comment by bfs18** [comment]
check if add_noise=True in wavenet_mol.json. It is a testing option, set it to false please.

**Comment by maozhiqiang** [comment]
when I training step< 100000, add_noise=True, when  step>100000 ! add_noise=False，Do I have to retrain？

**Comment by bfs18** [comment]
@maozhiqiang Hi, I haven't tested that. However retraining seems necessary according to your result.

**Comment by maozhiqiang** [comment]
@bfs18 thanks! I will try! the training is so slow with 4*16G GPU
